#include<iostream>

using namespace std;


void guardar_archivo(){
   	cuadro(4,45,11,30);
   	system("color 0f");
    string nombrearchivo;
   	ofstream f;
   	ventana_guardar_archivo();
	fflush(stdin);
	getline(cin,nombrearchivo);
   	f.open(nombrearchivo.c_str(),ios::out);
   	f<<" "<<endl;
   	f<<"                                <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
	f<<endl; 
	f<<"        COMPUTO DE MATERIALES"<<endl; 
	f<<"  ________________________________"<<endl;    
	f<<" "<<endl;  
	cout.precision(2);                                                                        
	f<<"  arena             : "<<tare<<" m3"<<endl;
	f<<"  cal               : "<<tcal<<" bolsas"<<endl;
    f<<"  cal aerea         : "<<tcalaer<<" bolsas"<<endl;
    f<<"  cemento           : "<<tcem<<" bolsas"<<endl;
	f<<"  piedra            : "<<tpie<<" m3"<<endl;
	f<<"  cascote           : "<<tcas<<" m3"<<endl;
	f<<"  hierro 6          : "<<thierro6<<" varillas"<<endl;
	f<<"  hierro 8          : "<<thierro8<<" varillas"<<endl;
	f<<"  hierro 10         : "<<thierro10<<" varillas"<<endl;
	f<<"  alambre negro     : "<<talam<<" kg"<<endl;
	cout.precision(5);    
	f<<"  ladrillos comunes : "<<tladcomun<<" unidades"<<endl;
	f<<"  ladrillos huecos  : "<<tladhueco<<" unidades"<<endl;
    f<<"  ladrillos bloque  : "<<tbloque<<" unidades"<<endl;
    f<<"  __________________________________"<<endl;
    f<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
	f.close();
}
void guardar_archivo_2(){
   	cuadro(4,45,11,30);
   	system("color 0f");
    string nombrearchivo;
   	ofstream f;
   	ventana_guardar_archivo();
	fflush(stdin);
	getline(cin,nombrearchivo);
   	f.open(nombrearchivo.c_str(),ios::out);
   	f<<" "<<endl;
   	f<<"                                <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
	f<<endl; 
	f<<"               COMPUTO DE MATERIALES"<<endl; 
	f<<"  _______________________________________________"<<endl;    
	f<<" "<<endl;    
	cout.precision(3);                                                   
	f<<"  Solera 35mm                  : "<<tsol35<<" un"<<endl;
	f<<"  Montante 34mm                : "<<tmon35<<" un"<<endl;
    f<<"  Solera 70mm                  : "<<tsol70<<" un"<<endl;
    f<<"  Montante 69mm                : "<<tmon70<<" un"<<endl;
	f<<"  Omega                        : "<<tomega<<" un"<<endl;
	f<<"  Placa yeso (12mm/9mm)        : "<<tplaca<<" un"<<endl;
	f<<"  Tornillos T1                 : "<<tt1<<" un x100"<<endl;
	f<<"  Tornillos T2                 : "<<tt2<<" un x100"<<endl;
	f<<"  Fijaciones (tarugo+tormillo) : "<<tfijaciones<<" un x100"<<endl;
	f<<"  Masilla                      : "<<tmasilla<<" un x 32kg"<<endl;
	f<<"  Cinta tramada/papel          : "<<tcinta<<" un x75mts"<<endl;
    f<<"  _______________________________________________"<<endl;
    f<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
	f.close();
}
void guardar_archivo_pyd(){
   	cuadro(4,46,2,66);
   	string nombrearchivopyd;
   	ofstream f;
   	ventana_guardar_archivo_pyd();
	fflush(stdin);
    gotoxy(87,4);getline(cin,nombrearchivopyd);
   	f.open(nombrearchivopyd.c_str(),ios::out);
	f<<"                              <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
    f<<"  DETERMINACION DE HONORARIOS POR PROYECTO Y DIRECCION"<<endl;
    f<<" "<<endl;
	f<<"  Superficie cubierta                       "<<sup_cub<<" m2"<<endl; 
	f<<"  Superficie semi cubierta                  "<<sup_scub<<" m2"<<endl; 
    f<<"  Monto de la obra                        $ "<<monto_obra<<endl; 
    f<<"  Hasta $ "<<hasta<<"                     $ "<<total_hasta<<endl;
    f<<"  el "<<porc<<" % s/los siguientes $ "<<siguientes<<"         $ "<<total_siguientes<<endl;
    f<<"                                    Total $ "<<total_hasta+total_siguientes<<endl;
    f<<"  Proyecto                                $ "<<proyecto<<endl;
	f<<"  Direccion                               $ "<<direccion<<endl;
	f<<"  Suplemento dir. cont. separados         $ "<<direccion_sep<<endl;
	f<<"  Suplemento dir. ejecutiva               $ "<<direccion_eje<<endl;
	f<<"  _____________________________________________________"<<endl; 
	f<<"  TOTAL CONTRATO                          $ "<<total_contrato<<endl;
	f<<" "<<endl; 
	f<<"  GASTOS PROFESIONAL"<<endl;
    f<<"  C.E.P.    (2.5%)                        $ "<<cep<<endl; 
	f<<"  Timbrado  (1,1%)                        $ "<<timbrado<<endl; 
	f<<"  Gastos C.A.I.T.B.A.                     $ "<<caitba<<endl; 
	f<<"  _____________________________________________________"<<endl; 
   	f<<"  TOTAL GASTOS                            $ "<<total_gastos<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
	f.close();
}
void guardar_archivo_art29(float computoypresup){
   	cuadro(4,46,2,66);
   	string nombrearchivoart29;
   	ofstream f;
   	ventana_guardar_archivo_pyd();
	fflush(stdin);
    gotoxy(87,4);getline(cin,nombrearchivoart29);
   	f.open(nombrearchivoart29.c_str(),ios::out);
	f<<" "<<endl;
	f<<"                              <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
	f<<endl; 
    f<<"  DETERMINACION DE ART. (29)"<<endl;
	f<<endl; 
    f<<"  Monto de obra s/computo y presupuesto   $ "<<computoypresup<<endl;
	f<<"  Articulo (29) 10%                       $ "<<total_computoypresup<<endl;
	f<<"  ________________________________________________________"<<endl;
	f<<"  TOTAL A PAGAR                           $ "<<total_computoypresup<<endl;
   	f<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
    gotoxy(119,29);
    f.close();	
}
void guardar_archivo_art29bis(){
   	cuadro(4,46,2,66);
   	string nombrearchivoart29;
   	ofstream f;
   	ventana_guardar_archivo_pyd();
	fflush(stdin);
    gotoxy(87,4);getline(cin,nombrearchivoart29);
   	f.open(nombrearchivoart29.c_str(),ios::out);
	f<<" "<<endl;
	f<<"                              <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
	f<<endl; 
    f<<"  DETERMINACION DE ART. (29)"<<endl;
	f<<endl; 
	f<<"  Superficie cubierta                       "<<sup_cub<<" m2"<<endl; 
	f<<"  Superficie semi cubierta                  "<<sup_scub<<" m2"<<endl; 
    f<<"  Monto de la obra                        $ "<<monto_obra<<endl;
	f<<"  Articulo (29) 10%                       $ "<<total_art29<<endl;
	f<<"  _____________________________________________________"<<endl;
	f<<"  TOTAL A PAGAR                           $ "<<total_art29<<endl;
   	f<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
    gotoxy(119,29);
    f.close();	
}
void guardar_archivo_med(){
   	cuadro(4,46,2,66);
   	string nombrearchivomed;
   	ofstream f;
   	ventana_guardar_archivo_pyd();
	fflush(stdin);
    gotoxy(87,4);getline(cin,nombrearchivomed);
   	f.open(nombrearchivomed.c_str(),ios::out);
	f<<" "<<endl;
	f<<"                              <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
	f<<endl; 
    f<<"  DETERMINACION DE HONORARIOS POR MEDICION e INFORME TECNICO"<<endl;
    f<<"  __________________________________________________________"<<endl; 
	f<<"  Superficie cubierta                       "<<sup_cub<<" m2"<<endl; 
	f<<"  Superficie semi cubierta                  "<<sup_scub<<" m2"<<endl; 
    f<<"  Monto de la obra                        $ "<<monto_obra<<endl; 
    f<<"  Hasta $ "<<hasta<<"                     $ "<<total_hasta<<endl;
    f<<"  el "<<porc<<" % s/los siguientes $ "<<siguientes<<"         $ "<<total_siguientes<<endl;
	f<<"                                    Total $ "<<total_hasta+total_siguientes<<endl;
    f<<" "<<endl;
    f<<"  Medicion                                $ "<<monto_obrafinal<<endl;
	f<<"  Informe Tecnico                         $ "<<informetec<<endl;
	f<<"  __________________________________________________________"<<endl; 
	f<<"  TOTAL CONTRATO                          $ "<<total_contrato<<endl;
	f<<"  __________________________________________________________"<<endl; 
	f<<"  GASTOS PROFESIONAL"<<endl;
    f<<"  C.E.P.    (2.5%)                        $ "<<cep<<endl; 
	f<<"  Timbrado  (1,1%)                        $ "<<timbrado<<endl; 
	f<<"  Gastos C.A.I.T.B.A.                     $ "<<caitba<<endl; 
	f<<"  _____________________________________________________"<<endl; 
   	f<<"  TOTAL GASTOS                            $ "<<total_gastos<<endl; 
   	f<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
    gotoxy(119,29);
    f.close();
}
void guardar_archivo_demolicion(){
	cuadro(4,46,2,66);
	string nombrearchivodemolicion;
   	ofstream f;
   	ventana_guardar_archivo_pyd();
	fflush(stdin);
    gotoxy(87,4);getline(cin,nombrearchivodemolicion);
   	f.open(nombrearchivodemolicion.c_str(),ios::out);
	f<<" "<<endl;
	f<<"                              <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
	f<<endl; 
    f<<"     DETERMINACION DE HONORARIOS POR  DEMOLICION"<<endl;
	f<<"  _________________________________________________"<<endl; 
	f<<"  Superficie cubierta                       "<<sup_cub<<" m2"<<endl; 
	f<<"  Superficie semi cubierta                  "<<sup_scub<<" m2"<<endl; 
    f<<"  Monto de la obra                        $ "<<monto_obra<<endl; 
    f<<"  Hasta $ "<<hasta<<"                     $ "<<total_hasta<<endl;
    f<<"  el "<<porc<<" % s/los siguientes $ "<<siguientes<<"         $ "<<total_siguientes<<endl;
	f<<"                                    Total $ "<<total_hasta+total_siguientes<<endl;
    f<<" "<<endl;
	f<<"  Direccion de demolicion  (16%)          $ "<<direccion_demolicion<<endl;
	f<<"  Suplemento dir. ejecutiva               $ "<<suplemento_demolicion<<endl; 
	f<<"  __________________________________________________"<<endl; 
	f<<"  TOTAL CONTRATO                          $ "<<total_contrato<<endl; 
	f<<"  __________________________________________________"<<endl; 
	f<<"  GASTOS PROFESIONAL"<<endl;
    f<<"  C.E.P.    (2.5%)                        $ "<<cep<<endl; 
	f<<"  Timbrado  (1,1%)                        $ "<<timbrado<<endl; 
	f<<"  Gastos C.A.I.T.B.A.                     $ "<<caitba<<endl; 
	f<<"  __________________________________________________"<<endl; 
   	f<<"  TOTAL GASTOS                            $ "<<total_gastos<<endl; 
   	f<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
    f.close();
}
void guardar_archivo_con(){
	cuadro(4,46,2,66);
	string nombrearchivoconstruccion;
   	ofstream f;
   	ventana_guardar_archivo_pyd();
	fflush(stdin);
    gotoxy(87,4);getline(cin,nombrearchivoconstruccion);
   	f.open(nombrearchivoconstruccion.c_str(),ios::out);
	f<<" "<<endl;
	f<<"                              <<< Sistema de calculos para MMO & ARQ >>>"<<endl;
    f<<"  ________________________________________________________________________________________________________________"<<endl; 
	f<<endl; 
    f<<"      DETERMINACION DE HONORARIOS POR  CONSTRUCCION"<<endl;
	f<<"  _____________________________________________________"<<endl; 
	f<<"  Superficie cubierta                       "<<sup_cub<<" m2"<<endl; 
	f<<"  Superficie semi cubierta                  "<<sup_scub<<" m2"<<endl; 
    f<<"  Monto de la obra                        $ "<<monto_obra<<endl; 
    f<<"  Hasta $ "<<hasta<<"                     $ "<<total_hasta<<endl;
    f<<"  el "<<porc<<" % s/los siguientes $ "<<siguientes<<"         $ "<<total_siguientes<<endl;
	f<<"                                    Total $ "<<total_hasta+total_siguientes<<endl;
	f<<"  Construccion                            $ "<<monto_obrafinal<<endl; 
	f<<"  _____________________________________________________"<<endl; 
	f<<"  TOTAL CONTRATO                          $ "<<monto_obrafinal<<endl; 
	f<<endl; 
	f<<"  _____________________________________________________"<<endl; 
	f<<"  GASTOS PROFESIONAL"<<endl;
    f<<"  C.E.P.    (2.5%)                        $ "<<cep<<endl; 
	f<<"  Timbrado  (1,1%)                        $ "<<timbrado<<endl; 
	f<<"  Gastos C.A.I.T.B.A.                     $ "<<caitba<<endl; 
	f<<"  _____________________________________________________"<<endl; 
   	f<<"  TOTAL GASTOS                            $ "<<total_gastos<<endl; 
   	f<<endl; 
   	f<<"  ________________________________________________________________________________________________________________"<<endl; 
   	f<<"  Creado por: MMO Gustavo Daniel Beltran - mat: 47820 - cel: (0223) 155-827063 - e-mail: gustavodbeltran@gmail.com"<<endl;
    f.close();
}
void leer_archivo(){
	borrar_fondosubmenu();
	cuadro(7,32,8,77);
	boton(2,30,9,78);
    boton(2,30,12,78);
    ifstream f;
    string nombrearchivo;
    gotoxy(79,10);cout<<"Ingrese el nombre del computo";
    SetConsoleTextAttribute (GetStdHandle(STD_OUTPUT_HANDLE),75);
    fflush(stdin);
	gotoxy(79,13);getline(cin,nombrearchivo);
	SetConsoleTextAttribute (GetStdHandle(STD_OUTPUT_HANDLE),017);
	system("cls");
//	cuadro(28,118,0,0);
   	f.open(nombrearchivo.c_str(),ios::in);
    string texto;
    int i=1;
    while(!f.eof()){
    	getline(f,texto);
    	gotoxy(1,i);cout<<texto<<endl;
    	i++;
    }
    f.close();
}

